// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CompDom: typeof import('./src/components/mainZone/components/compDom.vue')['default']
    Component: typeof import('./src/components/component.vue')['default']
    ComponentData: typeof import('./src/components/LeftZone/components/componentData.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LeftZone: typeof import('./src/components/LeftZone/index.vue')['default']
    Main: typeof import('./src/components/main/index.vue')['default']
    MainZone: typeof import('./src/components/mainZone/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
